// 앱(camelCase) ↔ Supabase applications 테이블(snake_case) 변환
import type { Application } from "@/types";

// 신청 제출 payload → DB row
export function toRow(p: any, applicantId?: string): Record<string, any> {
  return {
    applicant_id: applicantId ?? null,
    name: p.name,
    student_id: p.studentId,
    university: p.university,
    campus: p.campus || null,
    department: p.department,
    grade: p.grade,
    academic_status: p.academicStatus,
    grad_completion: p.gradCompletion || null,
    completed_years: p.completedYears || null,
    current_semester: p.currentSemester || null,
    phone: p.phone,
    email: p.email,
    application_date: p.applicationDate,
    bank_name: p.bankInfo?.bankName || null,
    account_number: p.bankInfo?.accountNumber || null,
    account_holder: p.bankInfo?.accountHolder || null,
    account_mismatch: !!p.accountMismatch,
    application_phase: p.applicationPhase || "fund",
    application_type: p.applicationType,
    program_detail: p.programDetail ?? null,
    staff_detail: p.staffDetail ?? null,
    grade_detail: p.gradeDetail ?? null,
    contest_detail: p.contestDetail ?? null,
    certificate_detail: p.certificateDetail ?? null,
    labor_detail: p.laborDetail ?? null,
    activity_detail: p.activityDetail ?? null,
    files: p.files ?? [],
    signature: p.signature || null,
    privacy_consent: !!p.privacyConsent,
    truth_consent: !!p.truthConsent,
    account_consent: !!p.accountConsent,
    request_amount: p.requestAmount ?? 0,
    calculated_amount: p.calculatedAmount ?? 0,
    is_draft: !!p.isDraft,
    draft_step: p.draftStep ?? null,
    is_test: !!p.isTest,
    verified_account: p.verifiedAccount ?? null,
    // 스키마 폼 답변이 있을 때만 포함(컬럼 미존재 환경에서 기존 제출이 깨지지 않도록)
    ...(p.formAnswers ? { form_answers: p.formAnswers } : {}),
  };
}

// DB row → Application
export function fromRow(r: any): Application {
  return {
    id: r.id,
    receiptNumber: r.receipt_number || "",
    createdAt: r.created_at,
    updatedAt: r.updated_at,
    name: r.name,
    studentId: r.student_id,
    university: r.university,
    campus: r.campus || undefined,
    department: r.department,
    grade: r.grade,
    academicStatus: r.academic_status,
    gradCompletion: r.grad_completion || undefined,
    completedYears: r.completed_years || undefined,
    currentSemester: r.current_semester || undefined,
    phone: r.phone,
    email: r.email,
    applicationDate: r.application_date,
    bankInfo: {
      bankName: r.bank_name || "",
      accountNumber: r.account_number || "",
      accountHolder: r.account_holder || "",
    },
    accountMismatch: r.account_mismatch ?? undefined,
    applicationPhase: r.application_phase || "fund",
    applicationType: r.application_type,
    programDetail: r.program_detail ?? undefined,
    staffDetail: r.staff_detail ?? undefined,
    gradeDetail: r.grade_detail ?? undefined,
    contestDetail: r.contest_detail ?? undefined,
    certificateDetail: r.certificate_detail ?? undefined,
    laborDetail: r.labor_detail ?? undefined,
    activityDetail: r.activity_detail ?? undefined,
    files: r.files ?? [],
    privacyConsent: !!r.privacy_consent,
    truthConsent: !!r.truth_consent,
    accountConsent: !!r.account_consent,
    signature: r.signature || undefined,
    reviewStatus: r.review_status,
    paymentStatus: r.payment_status,
    adminMemo: r.admin_memo || "",
    reviewStage: r.review_stage ?? undefined,
    handoffNote: r.handoff_note || undefined,
    approvedAmount: r.approved_amount ?? undefined,
    requestAmount: r.request_amount ?? 0,
    calculatedAmount: r.calculated_amount ?? 0,
    canceled: !!r.canceled,
    canceledAt: r.canceled_at || undefined,
    canceledIp: r.canceled_ip || undefined,
    isDraft: !!r.is_draft,
    draftStep: r.draft_step ?? undefined,
    isTest: !!r.is_test,
    verifiedAccount: r.verified_account ?? undefined,
    formAnswers: r.form_answers ?? undefined,
  };
}
